name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cityscapes:latest
    - name: login
      run: docker login -u ahmedayman4a -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Tag the Docker image
      run: docker tag cityscapes:latest ahmedayman4a/cityscapes:latest
    - name: push the Docker image
      run: docker push ahmedayman4a/cityscapes:latest
